New branch
FuelLabs/fuel-indexer pull request #1064
Opened 2023-07-05 18:14 UTC by calldelegation

- [ ] Please add proper labels
- [ ] If there is an issue associated with this PR, please link the issue (right-hand sidebar)
- [ ] If there is not an issue associated with this PR, add this PR to the "Fuel Indexer" project (right-hand sidebar)

### Description

Please include a short derscription of what this PR does.

### Testing steps

Please provide the _exact_ testing steps for the reviewer(s) if this PR requires testing.

### Changelog

Please add a neat Changelog info here according to our [Contributor's Guide](./CONTRIBUTING.md).

2023-07-05 18:15 UTC, calldelegation commented
Sorry for the pings still in draft

2023-07-11 15:03 UTC, deekerno requested changes

2023-07-11 15:03 UTC, deekerno commented on docs/src/getting-started/quickstart.md
> +Note: older versions of `fuel-indexer` might not work in this guide
Consider moving this line under the `fuelup self update` line and changing to:
> Check that you have the latest available version of `fuel-indexer` by ensuring that your toolchain is up-to-date.

It's a bit more helpful and doesn't make an assumption of the toolchain that they're using.

2023-07-11 15:33 UTC, ra0x3 commented on docs/src/getting-started/quickstart.md
> +In this Quickstart, we'll use Fuel's toolchain manager [`fuelup`](https://github.com/FuelLabs/fuelup) in order to install the `forc-index` component that we'll use to develop our indexer. There are a
@calldelegation defer'ing to @deekerno here but yes, short and sweet 😄

2023-07-11 17:56 UTC, calldelegation commented on docs/src/getting-started/quickstart.md
> +<!-- markdownlint-restore -->
Nope i agree with you here

2023-07-11 18:16 UTC, deekerno reviewed
I didn't realize this on the first review pass, but we're asking users to install Postgres but then we instruct them to use the embedded database feature. We should choose one and stick with it.

@ra0x3: What do you think?

2023-07-11 22:33 UTC, calldelegation commented
> I didn't realize this on the first review pass, but we're asking users to install Postgres but then we instruct them to use the embedded database feature. We should choose one and stick with it.
> 
> @ra0x3: What do you think?

From the conversation on slack

2023-08-01 15:24 UTC, ra0x3 commented
@calldelegation Following up here. Is this PR still being actively worked on?

2023-08-09 19:35 UTC, deekerno commented
Closing this for now. We'll be revamping a lot of our documentation as part of #1174, so we'll move any relevant changes into that.

Thanks! ❤️

2023-08-09 19:35 UTC, closed without merging