refactor: swap ID from u64 to String
FuelLabs/fuel-indexer pull request #1217
Opened 2023-08-07 19:38 UTC by ra0x3

Thanks for opening a PR with the Fuel Indexer project, please review the **Checklist** below and ensure you've completed all of the necessary steps to make this PR review as painless as possible.

### Checklist
- [ ] Ensure your top-level commit message is inline with our [contributor guidelines](./CONTRIBUTING.md).
- [ ] Please add proper labels.
- [ ] If there is an issue associated with this PR, please link the issue (right-hand sidebar)
- [ ] If there is not an issue associated with this PR, add this PR to the "Fuel Indexer" project (right-hand sidebar)
- [ ] Please allow Codeowners at least 24 hours to do a first-pass review.
- [ ] Please add thorougly detailed testing steps below.
- [ ] Please keep your Changelog message short and sweet.

### Description

Please include a short derscription of what this PR does.

### Testing steps

Please provide the _exact_ testing steps for the reviewer(s) if this PR requires testing.

### Changelog

Please add a neat Changelog info here according to our [Contributor's Guide](./CONTRIBUTING.md).

2023-08-16 21:15 UTC, ra0x3 commented on packages/fuel-indexer/src/executor.rs
> +                // Just an FYI this error below is not getting unwrapped into a panic...
FYI @lostman

2023-08-16 21:15 UTC, ra0x3 commented on packages/fuel-indexer-types/src/lib.rs
> -#[cfg(test)]
Not even sure we ever used these conversions

2023-08-16 21:17 UTC, ra0x3 commented on packages/fuel-indexer-tests/tests/graphql_server.rs
> -    // ID selection
- This part of the test was giving problems
- Something tells me it's related to passing the `ID` in here manually where `ID` was simply 1 - however, now, ID is now calculated differently

2023-08-17 19:47 UTC, deekerno requested changes
Running through your testing steps now; left a few questions/suggestions in the meantime.

2023-08-17 19:47 UTC, deekerno commented on packages/fuel-indexer-tests/tests/graphql_server.rs
> -    // ID selection
Can we create an issue to ensure that we re-add an ID selection test at some point?

2023-08-17 19:47 UTC, deekerno commented on packages/fuel-indexer-plugin/src/wasm.rs
> +            let buff = bincode::serialize(&id.to_string()).unwrap();
I _think_ we can remove this `.to_string()` call here as `SizedAsciiString` provides an `impl` for `Serialize`: https://github.com/FuelLabs/fuels-rs/blob/df21541b679bb90a1ee3e54f34a67b7037b40be7/packages/fuels-core/src/types/core/sized_ascii_string.rs#L162-L169.

Additionally, can we replace the `.unwrap()` with an `.expect()`?

2023-08-17 19:47 UTC, deekerno commented on packages/fuel-indexer/src/ffi.rs
> +    pub fn store(&mut self) -> &mut Store {
Could we add a doc comment for this new function?

2023-08-17 20:00 UTC, lostman commented on packages/fuel-indexer-api-server/src/uses.rs
> +        }
I wonder whether there is a better way of handling this pattern.

The error returned by `?` is generally logged somewhere up. We have a couple of error messages that repeat this way.

The advantage of the `error!` macro is the source location attribution.

Perhaps there is some way to have both concise code and precise location.

2023-08-17 20:08 UTC, lostman commented on packages/fuel-indexer-tests/indexers/fuel-indexer-test/fuel_indexer_test.yaml
> +graphql_schema: packages/fuel-indexer-tests/indexers/fuel-indexer-test/schema/fuel_indexer_test.graphql
`indexers` 👍

2023-08-17 20:25 UTC, deekerno approved these changes

2023-08-17 20:26 UTC, ra0x3 commented on packages/fuel-indexer-api-server/src/uses.rs
> +        }
@lostman 
- I agree it seems a bit...repetitive? 
- I think the main reason I bubbled things up in this way (and in executor/service) was to be almost annoyingly explicit with the path of the error (where we can trace the error's path just via looking at the logs)
  - I'm open to better ways to accomplish this

2023-08-17 20:47 UTC, merged