enhancement: Update --replace-indexer and add --remove-data V2
FuelLabs/fuel-indexer pull request #1225
Opened 2023-08-08 14:03 UTC by lostman

### Description

A redo of https://github.com/FuelLabs/fuel-indexer/pull/1146 but with the kill notification mechanism removed.

### Testing steps

#### This PR adds an automatic CI test:

https://github.com/FuelLabs/fuel-indexer/pull/1225/files#diff-61710fa718a25e0e49156f4ac2682a97e9eb0d9fb5cb5316f09f924dde896982R307

#### Manual testing:

1. Start the `fuel-indexer`:

```
cargo run -p fuel-indexer -- run --run-migrations --fuel-node-host beta-3.fuel.network --fuel-node-port 80
```

2. Deploy an indexer:

```
cargo run --release -p forc-index -- deploy --path examples/fuel-explorer/fuel-explorer
```

Expected result: indexer processing blocks.

3. Redeploy an indexer, and keep the data:

```
cargo run --release -p forc-index -- deploy --path examples/fuel-explorer/fuel-explorer --replace-indexer
```

Expected result: indexer is replaced, and it resumes from where `fuel-explorer` left off:

```
INFO fuel_indexer::service: 397: Resuming Indexer(fuellabs.explorer) from block 1760
```

4. Redeploy an indexer, and remove the data:

```
cargo run --release -p forc-index -- deploy --path examples/fuel-explorer/fuel-explorer --replace-indexer --remove-data
```

Expected result: the indexer restarts from block 1:

```
INFO fuel_indexer::service: 397: Resuming Indexer(fuellabs.explorer) from block 1
```

5. Modify the schema, and attempt to redeploy the indexer without removing the data:

```
echo "type Ty { id: ID! }" >> examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql 
```

```
chmod +x ./scripts/utils/build_modules.bash && ./scripts/utils/build_modules.bash
```

```
cargo run --release -p forc-index -- deploy --path examples/fuel-explorer/fuel-explorer --replace-indexer
```

Expected result: an error:

```
▹▹▹▹ 🚀 Deploying...
{
  "details": "Conflict: Indexer(fuel.explorer)'s schema has changed. Use --remove-data to replace the indexer.",
  "success": "false"
}
```

6. Redeploy the modified indexer and remove old data:

```
cargo run --release -p forc-index -- deploy --path examples/fuel-explorer/fuel-explorer --replace-indexer
```

Expected result: indexer restarts from block 1.

```
INFO fuel_indexer::service: 397: Resuming Indexer(fuellabs.explorer) from block 1
```

### Changelog
- Instead of the kill notification mechanism and removing/restarting the indexer in a single request, in this PR, `forc index deploy` first issues the `remove` command and then deploys the indexer as a separate command.
- The indexer commits no data when the kill switch is flipped on—it reverts the transaction. This is done in `handle_events`, which now takes `Arc<AtomicBool>`. This allows the indexer to shutdown gracefully and prevents any data from entering the DB after the tables have been removed and recreated for the replacement indexer.

Thoughts?

2023-08-16 20:25 UTC, ra0x3 commented on packages/fuel-indexer-tests/tests/indexing_postgres.rs
> +async fn test_replacing_an_indexer_and_keeping_or_removing_data() {
@lostman 
- This is a web server test (related to uploading/deploying indexers), not a test related to indexing data (triggering events, indexing the data)
- So we should move this to web_api_postgres.rs (I think that's the name of the module)

2023-08-17 20:48 UTC, ra0x3 commented
Sorry for the conflicts @lostman. I'm reviewing this now. Aiming to merge tomorrow 👌🏽

2023-08-18 08:30 UTC, lostman commented
@ra0x3, no worries. I'll fix the conflicts in the meantime.

2023-08-18 12:48 UTC, ra0x3 commented
@lostman 
- The testing steps (in both this PR and the linked PR) are unclear.
- You've added two options in this PR
- What is the expected result after running each option?

2023-08-18 13:36 UTC, ra0x3 requested changes
@lostman 
- Looks mostly ok thanks for getting back to this
- The only part I'm skeptical about is the change to `handle_events`
  - There are not details in the description (or anywhere else) that prove how passing a `kill_switch` to `handle_events` helps here
    - IMO, what you added on line 48 of `forc_index_deploy.rs` removes the need for this complexity 
- This work produced an issue in production last time, so that's the reason the review is more strict this time

2023-08-18 13:36 UTC, ra0x3 commented on packages/fuel-indexer-api-server/src/uses.rs
> +async fn parse_register_indexer_multipart(
👌🏽

2023-08-18 13:36 UTC, ra0x3 commented on packages/fuel-indexer-api-server/src/uses.rs
> +                continue;
Do we need this `continue` ?

2023-08-18 13:36 UTC, ra0x3 commented on packages/fuel-indexer-api-server/src/uses.rs
> +#[allow(clippy::too_many_arguments)]
- Let's remove this `#[allow(clippy::too_many_arguments)]` and adjust the code so that we don't need it 
- `namespace`, `identifier`, and `pubkey` are all a part of `RegisteredIndexer`
- `register_indexer_assets_transaction` fetches the `indexer_id` but you could adjust this to fetch the `RegisteredIndexer` using `namespace` and `identifier` via `get_indexer`

2023-08-18 13:36 UTC, ra0x3 commented on packages/fuel-indexer-api-server/src/uses.rs
> +                if queries::asset_already_exists(
- Not really a comment for this PR per-se
- But I (just now) confirmed that `asset_already_exists`'s `digest` resolves to the same hash as `GraphQLSchema.version()` (even though we're using we're using slightly different means of calculating the hash, which we should update/fix in https://github.com/FuelLabs/fuel-indexer/issues/1227

2023-08-18 13:36 UTC, ra0x3 commented on packages/fuel-indexer-api-server/src/uses.rs
> +                    return Err(ApiError::Http(HttpError::Conflict(format!(
👌🏽

2023-08-18 13:36 UTC, ra0x3 commented on packages/fuel-indexer-api-server/src/uses.rs
> +        error!("Failed to replace Indexer({namespace}.{identifier}): replacing an indexer is not enabled.");
👌🏽

2023-08-18 13:36 UTC, ra0x3 commented on packages/fuel-indexer-api-server/src/uses.rs
> +                let schema =
Don't we already have the `GraphQLSchema` on line 327?

2023-08-18 13:36 UTC, ra0x3 commented on packages/fuel-indexer-tests/tests/web_server.rs
> +async fn test_replacing_an_indexer_and_keeping_or_removing_data() {
Nice clean test 👌🏽

2023-08-18 13:36 UTC, ra0x3 commented on packages/fuel-indexer/src/database.rs
> +            let columns = self.schema.entry(table.to_string()).or_default();
👌🏽

2023-08-18 13:36 UTC, ra0x3 commented on plugins/forc-index/src/ops/forc_index_deploy.rs
> +    // issuer remove command. Ordinary reload is enough.
```suggestion
    // issue a remove command. Ordinary reload is enough.
```

2023-08-18 13:36 UTC, ra0x3 commented on plugins/forc-index/src/ops/forc_index_deploy.rs
> +    if replace_indexer && remove_data {
- This here is the reason I don't think we _really_ need the complexity of a `kill_switch` in `handle_events`.
- A three second wait here would be more than enough time for the tokio task to stop 
  - Just now testing on my machine on origin/develop - the explorer never takes more than 2 seconds to stop after calling `forc index remove`
  - Remember `forc index deploy` is literally a deployment (it posts assets, registers them in the DB, creates a new task, starts that task -- it does a lot)
    - An additional small delay will not disrupt any UX here (especially if it means less complexity elsewhere)

2023-08-18 14:19 UTC, lostman commented on plugins/forc-index/src/ops/forc_index_deploy.rs
> +    if replace_indexer && remove_data {
@ra0x3, It is possible for the remove and the deploy commands to execute, thus cleaning up the database and recreating the tables while the indexer is doing something. The indexer then finishes and commits the transaction, putting the data into newly created tables.

Why should we allow this possibility at all?

The `kill_switch` is already there in `run_executor.` All we need to do is to pass it to `handle_events` and abort the transaction. This gives us a clean and reliable behavior: no data is written to the DB after the kill switch has been flipped.

Currently, it can go either way—the indexer may write some data and then stop, or it may stop without writing any more data.

We could **also** add **early indexer termination**: since the kill switch is just an `AtomicBool,` we could check it each time `put_object` or `get_object` are called and terminate the (WASM) indexer then and there. That would be only slightly more complex but would have the benefit of clear and reliable behavior.

2023-08-18 14:44 UTC, ra0x3 commented on plugins/forc-index/src/ops/forc_index_deploy.rs
> +    if replace_indexer && remove_data {
@lostman 👌🏽

2023-08-22 11:22 UTC, lostman commented on packages/fuel-indexer-api-server/src/uses.rs
> +#[allow(clippy::too_many_arguments)]
`get_indexer` still needs `namespace` and `identifier`, so we only save `pubkey` as an argument.

This would avoid the clippy warning, but it isn't worth doing (this is a rather dubious warning).

We should use the `pubkey` we have in the API request, instead of fetching it from the DB. They should be the same, but still—it feels off.

Moreover, `get_indexer` returns a `Result<Option>`, so the unwrapping code gets more complicated. All of this is minor, but definitely not worth doing to avoid a clippy warning.

2023-08-29 14:07 UTC, ra0x3 requested changes
It works! 🏅 

Notes after manual testing

- Testing steps Fuel host needs to be updated to beta-4.fuel.network
- I noticed that I don't need to `--replace-indexer` when I `forc index deploy` in order for the indexer to be replaced
  - This PR should require that I include `--replace-indexer` if my intention is to replace the indexer
    - If I `forc index deploy` an existing indexer without `--replace-indexer` I should receive a 409 conflict error
    - **This is my only feedback from manual testing**
- When using `forc index deploy` with `--replace-indexer --remove-data`, my indexer is replaced and the data is removed 👍🏽 
  - However I do notice a lot of these logs
  - Log spam isn't the end of the world but might be a UX issue down the road (no biggie for now)

```
2023-08-29T14:02:35.598665Z ERROR fuel_indexer::database: 175: Failed to put_object: Database(PgDatabaseError { severity: Error, code: "25P02", message: "current transaction is aborted, commands ignored until end of transaction block", detail: None, hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("postgres.c"), line: Some(1438), routine: Some("exec_parse_message") })
```

2023-08-29 15:25 UTC, lostman commented
@ra0x3, my latest commit addresses the missing check for `--replace-indexer` flag from the CLI.

As for the log spam, once @deekerno adds return codes, I plan to use the kill switch to do proper early termination in WASM. This way, we won't be getting any of these errors.

2023-08-29 16:04 UTC, ra0x3 approved these changes

2023-08-29 16:05 UTC, merged

2023-08-29 16:05 UTC, ra0x3 commented
Given how long this has been outstanding, gonna go ahead and merge it so that it doesn't hang around any longer. Thanks @lostman