enhancement: Added message to compiler error when on Apple M1
FuelLabs/fuel-indexer pull request #1302
Opened 2023-08-27 20:27 UTC by dadepo

Currently opening as draft:
- To get feedback on the wording of the error message.
- @ra0x3 You left a comment [here](https://github.com/FuelLabs/fuel-indexer/issues/889#issuecomment-1543790207) stating:

> I might even go as far to say we maybe should read the output of a failed forc index build and look for wasm-related output in order to present this message their as well

Not sure I totally understand the requirement here and whether the changes in this PR already satisfies this.

### Description

Closes #889

### Changelog

- Added a private `error_message` function that, on compilation error, includes information about setting env variables if compilation fails on Apple M1s.

2023-08-28 12:13 UTC, ra0x3 commented
@dadepo 
- I think this is fair
- However, I do think this message should only be logged when the `-v --verbose` flag is included

2023-08-28 14:13 UTC, dadepo commented
> @dadepo
> 
> * I think this is fair
> * However, I do think this message should only be logged when the `-v --verbose` flag is included

@ra0x3 Updated to as suggested. I only extended the error message for one of the 3 error paths, as I was not sure if the other two can be due to the missing env variables.

2023-08-28 19:01 UTC, ra0x3 commented
@dadepo 
- Sorry CI is failing here :( still trying to get this release issue resolved
- In the meantime, this PR looks ok w/ me and I'll defer to @lostman or @deekerno for any additional feedback
- We will get this merged ASAP :)

2023-08-29 08:35 UTC, lostman requested changes
Looks good. Just requested minor corrections.

2023-08-29 08:35 UTC, lostman commented on plugins/forc-index/src/ops/forc_index_build.rs
> +and configuring rustc with necessary environment variables:
```suggestion
For Apple Silicon macOS users, the preinstalled llvm has limited WASM targets.
Please install a binary with better support from Homebrew (brew install llvm)
and configure rustc with the necessary environment variables:
```

Minor grammar corrections.

2023-08-29 09:31 UTC, dadepo commented
@lostman Thanks. I have accepted your suggestions.

2023-08-29 13:08 UTC, ra0x3 approved these changes

2023-08-29 14:00 UTC, lostman approved these changes

2023-08-29 16:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FuelLabs/fuel-indexer?pullRequest=1302) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/FuelLabs/fuel-indexer?pullRequest=1302) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dadepo<br/>:x: deekerno<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FuelLabs/fuel-indexer?pullRequest=1302) it.</sub>

2023-08-29 16:41 UTC, deekerno approved these changes

2023-08-30 22:30 UTC, merged