Made manifest contract_id work with both namespaced and non-namespaced contract IDs
FuelLabs/fuel-indexer pull request #1326
Opened 2023-09-02 10:06 UTC by dadepo

Closes [#1137](https://github.com/FuelLabs/fuel-indexer/issues/1137)

### Description

Made manifest contract_id work with both namespaced and non-namespaced contract IDs

### Changelog

Updated the logic that parses the address in the manifest to Bech32ContractId to work with both namespace and non-space addresses.

2023-09-05 20:00 UTC, ra0x3 requested changes
@dadepo 
- Looks mostly ok, left some minor feedback
- If you want to add a blurb to the docs, you can open `manifest.md`, go to the `contract_id` section, an add the following as a quote/blurb:

> Note that this parameter supports both Bech32 contract IDs and non-Bech32 contract IDs

2023-09-05 20:00 UTC, ra0x3 commented on examples/fuel-explorer/fuel-explorer/fuel_explorer.manifest.yaml
> +# Both namespaced contract IDs (e.g., 'fuels...') and
We can remove this added comment

2023-09-05 20:00 UTC, ra0x3 commented on examples/hello-world-native/hello-indexer-native/hello_indexer_native.manifest.yaml
> +# Both namespaced contract IDs (e.g., 'fuels...') and
We can remove this added comment

2023-09-05 20:00 UTC, ra0x3 commented on examples/hello-world/hello-indexer/hello_indexer.manifest.yaml
> +# Both namespaced contract IDs (e.g., 'fuels...') and
We can remove this added comment

2023-09-05 20:00 UTC, ra0x3 commented on packages/fuel-indexer-macros/src/indexer.rs
> +                        Bech32ContractId::from_str(#id).unwrap_or_else(|_| {
👌🏽

2023-09-05 20:00 UTC, ra0x3 commented on packages/fuel-indexer-tests/indexers/fuel-indexer-test/fuel_indexer_test.yaml
> +  - 0x0d50f87096474f43aabfa9abaa5fa65a3d3d0ff94998a5e2e7eb288d0c87384d
Let's remove `fuel1...` and just use `0x0d5...` - and if tests pass, that proves this works :)

2023-09-05 20:00 UTC, ra0x3 commented on plugins/forc-index/src/defaults.rs
> +# Both namespaced contract IDs (e.g., 'fuels...') and
We can remove this as well

2023-09-08 15:58 UTC, ra0x3 commented
@dadepo 

- This looks ok. Give us a bit of time and we'll get it merged for you :) 
- Really need to spend some time to figure out how to get 3rd-party contributors to run CI using the same tokens we (internal contributors) use

2023-09-11 21:13 UTC, deekerno approved these changes
I manually tested this and it works. 👌🏽

2023-09-11 22:12 UTC, merged