chore: fuel-indexer: refactor run, service, and executor to take advantage of tokio::task::JoinSet
FuelLabs/fuel-indexer pull request #1327
Opened 2023-09-04 10:36 UTC by lostman

### Description

This PR cleans up parts of `IndexerService`, `Executor`, and `fuel-indexer`'s `run.rs`.

There is a slight change of semantics due to the replacement of `FuturesUnordered` with `JoinSet`: `JoinSet` aborts all tasks when it is dropped. This appeared in `web-api` tests that dropped the `IndexerService` object before the tests' completion. Tasks added to `FuturesUnordered` would've been running anyway (since `task::spawn` detaches the future). Tasks spawned into the task set of `IndexerService` are aborted. This required a small change to the tests to keep the `IndexerService` alive.

### Testing steps

CI tests should pass.

### Changelog

* Replace `FuturesUnordered` with `tokio::task::JoinSet`
* Clean up code in `service.rs` and `executor.rs`: move the kill switch into `Executor` implementations and expose through the trait interface; expose the manifest the same way. This allows cleaning up some functions that now only need the executor and no other parameters.
* Simplify fuel-indexer's `run.rs` to use the `JoinSet` for all subsystems (node, web-api, signal-handler, etc.).
* `WasmIndexExecutor::new()` takes WASM bytes and not `ExecSource`: we were passing `ExecSource::Manifest` and returning `ExecSource::Registry(wasm_bytes)`. Instead, the WASM bytes are loaded before `new()` is called, and everything is simpler this way.
* `IndexerService::run` removes completed tasks from the `JoinSet` and runs the service loop: `loop { tokio::select! ... }`. This way, we don't need two separate tasks for it.

### Measuring resource usage:

Changes in this PR have no adverse effect on the resource usage:

<img width="1446" alt="Screenshot 2023-09-08 at 12 55 33 PM" src="https://github.com/FuelLabs/fuel-indexer/assets/1270689/f12843b0-5efb-4756-8534-ed37a3044a5e">

2023-09-11 21:43 UTC, deekerno requested changes
This looks pretty good! I like the cleanup. I left a few comments to be addressed before approval.

2023-09-11 21:43 UTC, deekerno commented on packages/fuel-indexer/src/commands/run.rs
> +// Returns a future which completes when a shutdown signal has been reveived.
s/reveived/received

2023-09-11 21:43 UTC, deekerno commented on packages/fuel-indexer/src/commands/run.rs
> +                    tracing::error!("Fuen Node failed: {e}");
s/Fuen/Fuel

2023-09-11 21:43 UTC, deekerno commented on packages/fuel-indexer/src/commands/run.rs
> +    subsystems.join_next().await;
If a service stops, does this actually cause the others to exit? Or are we relying on the fact that an error will be returned in the respective components and waiting for `join_next()` to catch it?

I don't mind this, but what do you think about something a bit more explicit?:
```
if let Some(_res) = subsystems.join_next().await {
    subsystems.shutdown().await;
}
```

2023-09-11 21:43 UTC, deekerno commented on packages/fuel-indexer/src/executor.rs
> +                );
We're no longer instantiating from an `ExecutorSource` here, so this error message should be adjusted.

2023-09-11 21:43 UTC, deekerno commented on packages/fuel-indexer/src/service.rs
> +    // the kill switch and the abort handle.ß
Looks like there's an errant `ß` here.

2023-09-12 08:13 UTC, lostman commented on packages/fuel-indexer/src/commands/run.rs
> +    subsystems.join_next().await;
I like your suggestion.

If a subsystem stops, the others don't exit automatically. I was relying here on this `await` holding the `main` running. After this `await`, all that is left is the database cleanup and the `main` exits. Shutting things down explicitly is cleaner.

2023-09-12 13:39 UTC, deekerno approved these changes
🆗

2023-09-12 13:40 UTC, merged