chore: nice errors on failed forc-index-deploy
FuelLabs/fuel-indexer pull request #1408
Opened 2023-10-11 15:32 UTC by ra0x3

Thanks for opening a PR with the Fuel Indexer project. Please review the **Checklist** below and ensure you've completed all of the necessary steps to make this PR review as painless as possible.

### Checklist
- [ ] Ensure your top-level commit message is in line with our [contributor guidelines](./CONTRIBUTING.md).
- [ ] Please add proper labels.
- [ ] If there is an issue associated with this PR, please link the issue (right-hand sidebar)
- [ ] If there is not an issue associated with this PR, add this PR to the "Fuel Indexer" project (right-hand sidebar)
- [ ] Please allow Codeowners at least 24 hours to do a first-pass review.
- [ ] Please add thoroughly detailed testing steps below.
- [ ] Please keep your Changelog message short and sweet.

### Description

Please include a short description of what this PR does.

### Testing steps

Please provide the _exact_ testing steps for the reviewer(s) if this PR requires testing.

### Changelog

Please add neat Changelog info here, according to our [Contributor's Guide](./CONTRIBUTING.md).

2023-10-12 10:18 UTC, lostman requested changes

2023-10-12 10:18 UTC, lostman commented on plugins/forc-index/src/ops/forc_index_deploy.rs
> +            error!("❌ Failed to deploy indexer: {e:?}");
```suggestion
            error!("❌ Failed to deploy indexer: {e}");
```

`{e:?}` still prints a non-user-friendly error message:
```
❌ Failed to deploy indexer: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(29987), path: "/api/index/fuellabs/explorer", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })) }
```

If we change it to `{e}`, we'll get:
```
❌ Failed to deploy indexer: error sending request for url (http://127.0.0.1:29987/api/index/fuellabs/explorer): error trying to connect: tcp connect error: Connection refused (os error 61)
```

2023-10-12 12:39 UTC, lostman approved these changes

2023-10-13 15:26 UTC, deekerno approved these changes

2023-10-13 15:37 UTC, merged