enhancement: forc index status: report indexer status and errors
FuelLabs/fuel-indexer pull request #1412
Opened 2023-10-13 17:15 UTC by lostman

### Description

Closes #1316.

This PR adds information about active indexers to `forc index status`.

### Testing steps

Start Fuel Indexer Service:
```
cargo run -p fuel-indexer -- run --fuel-node-host beta-4.fuel.network --fuel-node-port 80 --replace-indexer
```

Modify `fuel-explorer` to trigger a panic:

```
    fn index_block(block_data: BlockData) {
        let _x: Option<usize> = None.unwrap();
        ...
    }
```

Deploy:
```
forc-index deploy --path examples/fuel-explorer/fuel-explorer
```

Deploy another indexer:
```
forc-index deploy --path examples/hello-world/hello-world/
```

Check the status

```
cargo run -p forc-index -- status
```

![Screenshot 2023-10-17 at 5 09 32 PM](https://github.com/FuelLabs/fuel-indexer/assets/1270689/9d601ed9-b740-4ce0-b52f-741856f43ff2)

`fuel-explorer`'s status should be an `error` while the other indexer's status should be `running`, and the status message should show an increasing block count.

### Changelog

* Add additional information to `forc index status`
* Add `IndexerStatus` and `IndexerStatusKind` types
* Create `index_status` table to hold the new information
* Add `humantime` formatting of `created at`, e.g. `(23 min 30s ago)`

2023-10-17 20:21 UTC, deekerno submitted a review, later dismissed
This is excellent. Thanks @lostman!

2023-10-17 20:21 UTC, deekerno commented on packages/fuel-indexer-database/postgres/src/lib.rs
> +/// Set the status of a registered indexers to be displayed by `forc index status`.
s/indexers/indexer

2023-10-17 20:21 UTC, deekerno commented on packages/fuel-indexer-database/src/queries.rs
> +/// Set the status of a registered indexers to be displayed by `forc index status`.
s/indexers/indexer

2023-10-18 15:29 UTC, ra0x3 reviewed
@lostman 
- This mostly looks OK
- However, I'm personally not sure how this works
- Does this work for a single indexer? For a single public key? This works for all indexers under a given public key? What if I want to check the status of a single indexer?
  - If these have simple answers, I don't think we need docs
  - If these answers are a bit more invovled, maybe we'll have to add a `## Usage` section in ` docs > src > forc-index > status.md`

2023-10-18 15:29 UTC, ra0x3 commented on packages/fuel-indexer-database/postgres/migrations/20231012190730_indexer_status.up.sql
> +   id bigserial primary key,
@lostman Should this not be a foreign key to `index_registry`?

2023-10-18 15:40 UTC, lostman commented on packages/fuel-indexer-database/postgres/migrations/20231012190730_indexer_status.up.sql
> +   id bigserial primary key,
> Does this work for a single indexer? For a single public key? This works for all indexers under a given public key? What if I want to check the status of a single indexer?

If `fuel-indexer` does not require authentication, the output is all indexers with all the keys.

If `fuel-indexer` does require authentication, the output is the indexers for one's key.

There is no way to select a single indexer. It could be added easily. Something like:

```
forc index status fuellabs.explorer
```

I can add it to this PR if you'd like

2023-10-18 15:53 UTC, ra0x3 commented on packages/fuel-indexer-database/postgres/migrations/20231012190730_indexer_status.up.sql
> +   id bigserial primary key,
@lostman No this is fine as is :)

2023-10-18 15:54 UTC, ra0x3 commented on packages/fuel-indexer-database/postgres/migrations/20231012190730_indexer_status.up.sql
> +   id bigserial primary key,
@lostman Also, I see you commented under this particular comment about the foreign key 😆 . So before I resolve this thread, was there a reason `index_status` doesn't use a foreign key pointing to `index_registry` ?

2023-10-18 17:26 UTC, ra0x3 requested changes

2023-10-18 17:26 UTC, ra0x3 commented on packages/fuel-indexer-database/postgres/migrations/20231012190730_indexer_status.up.sql
> +   namespace varchar(32) not null,
@lostman If we're keeping track of indexer info in `index_registry` and using a foreign key for `index_status` do we need to also keep the namespace and identifier here as well?

2023-10-18 18:37 UTC, lostman commented on packages/fuel-indexer-database/postgres/migrations/20231012190730_indexer_status.up.sql
> +   namespace varchar(32) not null,
Nope, we don't! Changed it in the latest commit.

2023-10-18 18:39 UTC, ra0x3 submitted a review, later dismissed

2023-10-18 18:42 UTC, deekerno approved these changes, later dismissed

2023-10-18 20:59 UTC, ra0x3 approved these changes

2023-10-18 21:17 UTC, deekerno approved these changes

2023-10-18 21:17 UTC, merged