enhancement: implement find on entity
FuelLabs/fuel-indexer pull request #1446
Opened 2023-11-02 15:02 UTC by lostman

### Description

Closes https://github.com/FuelLabs/fuel-indexer/issues/1437.

Example usage:

```rust
// Test searching for a string field
let f = FindEntity::find(
    FindEntity::string_value()
        .gt("f".to_string())
        .order_by_asc(FindEntity::value()),
)
```

This PR extends the codegen to generate field selectors for an `@entity`, e.g.:

```rust
1460   │     pub fn id() -> Field<ChainInfo, ID> {
1461   │         Field::new("id".to_string())
1462   │     }
1463   │     pub fn base_chain_height() -> Field<ChainInfo, U32> {
1464   │         Field::new("base_chain_height".to_string())
1465   │     }
1466   │     pub fn name() -> Field<ChainInfo, String> {
1467   │         Field::new("name".to_string())
1468   │     }
1469   │     pub fn peer_count() -> Field<ChainInfo, I32> {
1470   │         Field::new("peer_count".to_string())
1471   │     }
1472   │     pub fn latest_block() -> Field<ChainInfo, UID> {
1473   │         Field::new("latest_block".to_string())
1474   │     }
1475   │     pub fn consensus_parameters() -> Field<ChainInfo, UID> {
1476   │         Field::new("consensus_parameters".to_string())
1477   │     }
```

`Field<T>` structs implement methods such as `eq`, `gt`, `lt`, etc., which return a `Filter<T>`, which, in turn, can be combined using `and` and `or` to produce a mode complex `Filter<T>`. Finally, a `Filter<T>` can be ordered ascending or descending, turning it into a `QueryFragment<T>`.

The `find` function on `Entity` takes a `Filter` or `QueryFragment` and fetches the corresponding object from the database, if any exists.

### Testing steps

CI testing. This PR includes an integration test for added functionality.

### Changelog

* Add `find(query: impl Into<QueryFragment<Self>>) -> Option<Self>` to `Entity`.
* Add `ff_single_select` to FFI, and `single_select` to the indexer.
* Add `fuel_indexer_plugin::find` module, which contains the code for generating SQL query fragments.
* Decoder now generates `field_selectors`, e.g., `pub fn base_chain_height() -> Field<ChainInfo, U32>` which are used to construct queries

2023-11-10 15:42 UTC, ra0x3 requested changes
- Wow @lostman very well done 👏🏼 
- Very clean and sets us up in a good spot to extend and continue the ORM work
- ⭐ ⭐⭐⭐⭐
- I left a comment about the syntax of your order clause. That's my only real feedback
- The rustdoc comments make this pretty easy to follow thankfully 🙏🏼

2023-11-10 15:42 UTC, ra0x3 commented on packages/fuel-indexer-plugin/src/find.rs
> +/// Convert `QueryFragment` to `String`. `SELECT * from table_name` is lated
```suggestion
/// Convert `QueryFragment` to `String`. `SELECT * from table_name` is later
```

2023-11-10 15:42 UTC, ra0x3 commented on packages/fuel-indexer-plugin/src/find.rs
> +    pub fn and(self, right: Filter<T>) -> Filter<T> {
Elegant usage of `sqlparser` here ❤️

2023-11-10 15:42 UTC, ra0x3 commented on packages/fuel-indexer-plugin/src/find.rs
> +    pub fn order_by_asc<F>(self, f: Field<T, F>) -> QueryFragment<T> {
- So for this,  I think the more ORM way to do `order by` is to follow the SQL syntax.
- In SQL, order by is:

```
SELECT foo
FROM bar
ORDER BY {field} {direction}
```

- Where `{direction}` is `ASC/DESC` and `{field}` is obviously the field you're ordering by.
- I think functionally what you have is roughly the same as that ☝🏼 
- But syntactically, it's not "SQL"
- Some links
  - [`order_by`](https://docs.djangoproject.com/en/4.2/ref/models/querysets/#django.db.models.query.QuerySet.order_by) in Django
    - You first declare your field, then you declare how to order it
  - [`order_by`](https://sequelize.org/docs/v6/core-concepts/model-querying-basics/#ordering-and-grouping) in Sequelize
    - Again, you first declare what to order, then how to order it 
  - Finally, [`order_by`](https://docs.diesel.rs/2.0.x/diesel/prelude/trait.QueryDsl.html#method.order_by) in Diesel 
    - Again, declaring what to order first, then how to order it

So I think a small change to something like:

```rust
Struct::find(Struct::field().eq(5).order_by(Struct::field().desc()); // like diesel
```
OR
```rust
Struct::find(Struct::field().eq(5).order_by(Struct::field(), Order::DESC));
```

2023-11-10 15:42 UTC, ra0x3 commented on packages/fuel-indexer-plugin/src/find.rs
> +    pub fn order_by_desc<F>(self, f: Field<T, F>) -> QueryFragment<T> {
Same comment as above with regard to declaring the field first, then the ordering

2023-11-10 15:42 UTC, ra0x3 commented on packages/fuel-indexer-tests/contracts/fuel-indexer-test/Forc.lock
> +name = "core"
@lostman 
- So if you want to upgrade Sway to 0.46 is this PR that's fine with me - I believe beta-4 is on 0.46 now anyway
- But let's make sure to upgrade _all_ smart contracts to 0.46 in a single go (for the ones that aren't on 0.46 already, assuming there are any)

2023-11-10 21:47 UTC, lostman commented on packages/fuel-indexer-plugin/src/find.rs
> +    pub fn order_by_asc<F>(self, f: Field<T, F>) -> QueryFragment<T> {
@ra0x3 

Sure, the syntax would be:

```rust
Struct::find(Struct::field().eq(5).order_by(Struct::field()).desc();
```

Or, we can add support for multiple fields from the get-go:

```rust
Struct::find(Struct::field().eq(5).order_by(vec![Struct::field()]).desc();
```

Or, this could also work, although my preference would be for the `vec!` as a cleaner solution:

```rust
Struct::find(Struct::field().eq(5).order_by(Struct::field()).order_by(Struct::another_field()).desc();
```

Finally, the syntax would allow for:

```rust
Struct::find(Struct::field().eq(5).order_by(Struct::field()).asc().desc().desc().asc();
```

Unless I add another struct that blocks it. It shouldn't be a problem for now though.

2023-11-16 15:51 UTC, ra0x3 approved these changes
🥇

2023-11-17 18:00 UTC, deekerno approved these changes
Looks great, just left one comment about the usage of `.unwrap()`.

2023-11-17 18:00 UTC, deekerno commented on packages/fuel-indexer-plugin/src/wasm.rs
> +    }
Can we get rid of the `.unwrap()`s here? From what I can tell, the other functions in this module don't use them.

2023-11-20 14:56 UTC, merged