chore: add --network to fuel-indexer
FuelLabs/fuel-indexer pull request #1457
Opened 2023-11-07 19:56 UTC by ra0x3

Thanks for opening a PR with the Fuel Indexer project. Please review the **Checklist** below and ensure you've completed all of the necessary steps to make this PR review as painless as possible.

### Checklist
- [ ] Ensure your top-level commit message is in line with our [contributor guidelines](./CONTRIBUTING.md).
- [ ] Please add proper labels.
- [ ] If there is an issue associated with this PR, please link the issue (right-hand sidebar)
- [ ] If there is not an issue associated with this PR, add this PR to the "Fuel Indexer" project (right-hand sidebar)
- [ ] Please allow Codeowners at least 24 hours to do a first-pass review.
- [ ] Please add thoroughly detailed testing steps below.
- [ ] Please keep your Changelog message short and sweet.

### Description

Please include a short description of what this PR does.

### Testing steps

Please provide the _exact_ testing steps for the reviewer(s) if this PR requires testing.

### Changelog

- chore: add --network to fuel-indexer

2023-11-07 21:37 UTC, lostman requested changes

2023-11-07 21:37 UTC, lostman commented on docs/src/getting-started/indexer-service-infrastructure.md
> +            Use a network alias when connecting to a Fuel client. [default: beta-3 beta-4 beta-5]
```suggestion
            Use a network alias when connecting to a Fuel client, such as beta-3, beta-4, beta-5, etc. [default: beta-3]
```

With `[default: beta-3 beta-4 beta-5]`, which is the default? `beta-3`?

2023-11-07 21:37 UTC, lostman commented on docs/src/getting-started/indexer-service-infrastructure.md
> +            Use a network alias when connecting to a Fuel client. [default: beta-3 beta-4 beta-5]
Same as above.

2023-11-08 15:56 UTC, lostman approved these changes

2023-11-08 15:58 UTC, deekerno approved these changes

2023-11-08 16:05 UTC, merged