enhancement: add find_many
FuelLabs/fuel-indexer pull request #1469
Opened 2023-11-22 12:56 UTC by lostman

### Description

Closes #1467.

This PR adds the `find_many()` function to the `Entity` trait, which is like `find()`, except that it fetches multiple results.

### Testing steps

CI tests should pass. This PR adds basic `find_many` tests to the existing `find` test.

### Changelog

* Add `find_many` to the `Entity` trait.
* Rename `QueryFragment` to `OrderedFilter`. This way we have `Filter` and `OrderedFilter`, which easier to understand.
* Clean up some implementation details.

2023-11-27 15:30 UTC, ra0x3 requested changes
@lostman 

- Left feedback regarding the usage of `limit` in your `find_many` implementation
- Will review again once that's fixed (since I think fixing that will shift some logic around)

2023-11-27 15:30 UTC, ra0x3 commented on packages/fuel-indexer-plugin/src/wasm.rs
> +    fn find_many(limit: usize, query: impl ToFilter<Self>) -> Vec<Self> {
- So the semantics of this `find_many` are a bit off.
- The `LIMIT` clause in SQL works similar to the `ORDER BY` clause
- In the `find` implementation https://github.com/FuelLabs/fuel-indexer/pull/1446, we added the `order_by` clause as a separate method

```rust
Entity::find(Entity::field().eq(value).order_by(Entity::field()).asc())
```
- The `LIMIT` clause works in a similar way - as a separate method
```rust
Entity::find(Entity::field().eq(value).order_by(Entity::field()).asc().limit(5))
```
- With that said, `.limit()` is a separate piece of functionality from `.find_many`
  - Totally fine if you want to go ahead and throw both of those in the same PR
  - When I mentioned "limit the result set" in the original issue, I was more so making sure we're aware of how much space we're allocating in the runtime for the result set

References
- [Sequelize `limit`](https://sequelize.org/docs/v6/core-concepts/model-querying-basics/#limits-and-pagination)
- [Django](https://docs.djangoproject.com/en/dev/topics/db/queries/#limiting-querysets) is actually notoriously known for not having a `.limit()` API 😆 
- [Diesel `.limit()`](https://docs.diesel.rs/2.0.x/diesel/prelude/trait.QueryDsl.html#method.limit)

2023-11-28 13:59 UTC, lostman commented on packages/fuel-indexer-plugin/src/wasm.rs
> +    fn find_many(limit: usize, query: impl ToFilter<Self>) -> Vec<Self> {
Thanks @ra0x3. I've changed the API to be like you described.

2023-11-28 18:06 UTC, ra0x3 approved these changes
Thanks @lostman

2023-11-29 03:20 UTC, deekerno approved these changes

2023-11-29 09:20 UTC, merged