Send block data to indexer
FuelLabs/fuel-indexer pull request #178
Opened 2022-08-29 20:21 UTC by tjsharp1

Still have some tests to fix up, but opening the draft now, in case people want to start looking at it.

2022-09-06 23:05 UTC, ra0x3 requested changes
@tjsharp1 

- Thanks for this 🙏 
- Obviously it's a really big/impactful API change so left a few more comments than usual
  - Mainly some questions 
- I pulled this down to test, and managed to get the `simple-native` example working (but had to change it to use WASM cause native wasn't working -- which is fine)
- Still trying to get the E2E test working

2022-09-06 23:05 UTC, ra0x3 commented on fuel-indexer/src/manifest.rs
> +    pub indexer_port: Option<u16>,
Can we not use `IndexerConfig` for this?

2022-09-06 23:05 UTC, ra0x3 commented on fuel-indexer/src/service.rs
> +                    retry_count += 1;
https://github.com/FuelLabs/fuel-indexer/issues/194

2022-09-06 23:37 UTC, ra0x3 commented on tests/e2e/composable-indexer/composable-indexer-lib/src/lib.rs
> +    fn function_one(ping: Ping) {
Last thing (forgot to leave this in the original review).
- So how is block/transaction indexing going to work here?
  - Would we write special handlers for `Block`s and/or `Transaction`s ?
  - For example, what if I wanted access to a `Block` here for indexing (e.g., SwaySwap)
    - Or would this behavior lie somewhere else entirely? 🤔

2022-09-07 02:00 UTC, deekerno reviewed
Mostly the same concerns as @ra0x3 regarding leftover files and potentially leftover comments, but it looks good overall so far.

2022-09-07 19:48 UTC, ra0x3 commented on fuel-indexer/src/service.rs
> +                    retry_count += 1;
Yea I didn't mean do this in this PR. Down the road

2022-09-07 19:49 UTC, ra0x3 commented on tests/e2e/composable-indexer/composable-indexer-lib/src/lib.rs
> +    fn function_one(ping: Ping) {
Yea if that's too much for this PR we can always follow up. But will need that before we can start indexing blocks I believe

2022-09-07 19:50 UTC, ra0x3 commented on fuel-indexer-macros/test_data/fail_args.stderr
> +error: abi specification is required in indexer definition!
@tjsharp1 
- Are they needed for the service to run? They look like dev files (files you keep locally while you're working on things).
- If at all possible, maybe we can `.gitignore` them, remove them from the repo, that way everyone just has them locally and not in the repo?

2022-09-07 19:50 UTC, ra0x3 commented on fuel-indexer/src/executor.rs
> +                return Err(IndexerError::HandlerError);
You are correct. My mistake here.

2022-09-07 23:44 UTC, ra0x3 commented
@tjsharp1 
- Sorry for the conflicts :(
- I have a local branch with a few minor changes to this work (updates to an example, and to the e2e test) that I will probably push up soon
- But locally (with those mentioned changes) this PR seem to work for me 👌 
- Approved :shipit: 
- Can give the official ✅ when the conflicts are fixed

2022-09-08 10:09 UTC, merged