Swap all unwrap() for expect()
FuelLabs/fuel-indexer pull request #191
Opened 2022-09-05 23:00 UTC by deekerno

## Description
As requested in #188, this PR swaps `.unwrap()` for `.expect()` in the production code. Testing code was not adjusted as it won't be called when running in production.

2022-09-06 22:09 UTC, ra0x3 requested changes
@deekerno 
- First PR 🥳  
- Looks pretty OK to me
- ~~[However, looks like there's still one `unwrap` remaining?](https://github.com/FuelLabs/fuel-indexer/blob/ab27c70f29f3b47ad32317a4d70b049a3f2ac9e0/database/postgres/src/lib.rs#L190)~~
- LGTM :shipit: 

P.S. Not sure if we want to wait for https://github.com/FuelLabs/fuel-indexer/pull/178 since definitely don't wanna keep that one outstanding too long (plus any conflicts if that gets merged first will be pretty small)

2022-09-06 22:09 UTC, ra0x3 submitted a review, later dismissed

2022-09-07 00:06 UTC, mitchmindtree approved these changes
To the first! :clinking_glasses: :tada:

:ship:

2022-09-07 01:33 UTC, deekerno commented
@ra0x3 Ah, the GitHub email didn't show had crossed out the line for the last remaining unwrap. 😅 If you don't mind re-approving, that would be great.

Also, I have no problem waiting for #178. 👍🏽

2022-09-07 01:36 UTC, mitchmindtree approved these changes

2022-09-07 01:37 UTC, ra0x3 approved these changes

2022-09-07 21:00 UTC, merged