Add asset upload functionality
FuelLabs/fuel-indexer pull request #203
Opened 2022-09-09 22:35 UTC by ra0x3

2022-09-13 16:38 UTC, deekerno requested changes

2022-09-13 16:38 UTC, deekerno commented on fuel-indexer/src/manifest.rs
> +            .expect("Failed here")
Could we put a more descriptive message here?

2022-09-13 16:38 UTC, deekerno commented on fuel-indexer/src/config.rs
> +    // FIXME
Is this still needed? If so, can we put a more descriptive message here?

2022-09-14 00:41 UTC, ra0x3 commented
@deekerno 
- Agree with all the feedback so far. 
- If there's no other feedback after a few days I'll merge as is and follow up in a small PR (so as to minimize the review noise).
- If there is other feedback I'll just make the changes in this PR

2022-09-14 04:28 UTC, deekerno approved these changes

2022-09-14 20:23 UTC, ra0x3 commented on fuel-indexer/src/api.rs
> +            .expect("Failed to get database connection.");
https://github.com/FuelLabs/fuel-indexer/issues/215

2022-09-14 20:25 UTC, ra0x3 commented on fuel-indexer/src/api.rs
> +            .route("/:namespace/:identifier", post(register_index_assets))
@tjsharp1 
- Yea that's the idea. `namespace` is your org, `identifier` is the name of that index running for that org
- You're right we'll eventually want friendly messaging around what namespace's are available
  - We would first need to implement some actual form of user authentication so namespaces can be tied to authenticated users

2022-09-14 22:04 UTC, deekerno approved these changes

2022-09-14 22:18 UTC, merged