docs: update contrib doc
FuelLabs/fuel-indexer pull request #477
Opened 2023-01-12 21:50 UTC by ra0x3

2023-01-12 23:25 UTC, deekerno requested changes

2023-01-12 23:25 UTC, deekerno commented on docs/CONTRIBUTING.md
> +If you are planning something big, for example, relates to multiple components or changes current behaviors, make sure to open an issue to discuss with us before continuing.
Consider:
> If you are planning something that changes current behaviors or relates to multiple components, ...

2023-01-12 23:25 UTC, deekerno commented on docs/CONTRIBUTING.md
> +    - So on and so forth
Nit: Remove this line, and un-indent "Keeping..." as they're not examples.

2023-01-13 01:18 UTC, hrryndrsn submitted a review, later dismissed
Looks good 👍

2023-01-13 18:14 UTC, deekerno approved these changes
👍🏽

2023-01-13 18:14 UTC, merged