docs: refactor book
FuelLabs/fuel-indexer pull request #492
Opened 2023-01-19 04:45 UTC by deekerno

Closes #489.

## Changelog
- Break up structure into _User Guide_ and _Reference Guide_ main sections

2023-01-21 00:26 UTC, ra0x3 requested changes
- I was gonna leave a ton of comments but I feel like that might not be the best way to review this.
- We have the new README [in this PR](https://github.com/FuelLabs/fuel-indexer/pull/492/files) and we have the new book in your/this PR.
- It's a bit of a chicken/egg thing (kinda) but we need to make sure there is parity between the book and the README
  - Obviously the book has to communicate more info, but they should be somewhat similar in their structure
-  I think the "User Guide" section looks good and simple
  - I would cleanup the "Installation" section
    - I imagine the "Installation" section would include the "Dependencies" section from the README 
- I'm "Requesting Changes" but only with regard to _how_ we should review this
  - Synchronously? That might lowkey be faster. I imagine there's gonna be  a _ton_ of feedback on this

There's obviously more to say here. But mainly want to figure out what you think might be the best method for communicating all of this feedback - keeping in mind the feedback for the README could also be related to the feedback for the book?

Overall, good stuff (docs are hard 🥲 ) the book already looks _much_ better and more streamlined.

2023-01-21 00:26 UTC, ra0x3 commented on docs/src/SUMMARY.md
> +# User Guide
I like the "User Guide" and "Reference Guide" breakdown (feel free to add the inspiration for that to the PR description - for others who might be curious where this breakdown comes from)

2023-01-21 00:31 UTC, deekerno commented
> * I was gonna leave a ton of comments but I feel like that might not be the best way to review this.
> 
>     * We have the new README [in this PR](https://github.com/FuelLabs/fuel-indexer/pull/492/files) and we have the new book in your/this PR.
> 
>     * It's a bit of a chicken/egg thing (kinda) but we need to make sure there is parity between the book and the README
>       
>       * Obviously the book has to communicate more info, but they should be somewhat similar in their structure
> 
>     * I think the "User Guide" section looks good and simple
> 
>     * I would cleanup the "Installation" section
>       
>       * I imagine the "Installation" section would include the "Dependencies" section from the README
> 
>     * I'm "Requesting Changes" but only with regard to _how_ we should review this
>       
>       * Synchronously? That might lowkey be faster. I imagine there's gonna be  a _ton_ of feedback on this
> 
> 
> There's obviously more to say here. But mainly want to figure out what you think might be the best method for communicating all of this feedback - keeping in mind the feedback for the README could also be related to the feedback for the book?
> 
> Overall, good stuff (docs are hard 🥲 ) the book already looks _much_ better and more streamlined.

I don't mind reviewing the README first to determine what should go in and then making sure that the book achieves parity afterwards. We'll be able to lift a lot of stuff from the README and include it in the book without much modification.

As far as reviewing it, I think that synchronous communication would be faster and I don't want to be stuck on docs much longer. 😅 I'll hit you up out-of-band to set that up.

2023-01-27 03:36 UTC, ra0x3 approved these changes
A true labor of love. I think this lays the foundation for a great book going forward 🙏

2023-01-27 04:07 UTC, merged