enhancement: add local-fuel-node arg to spin one up
FuelLabs/fuel-indexer pull request #564
Opened 2023-02-09 18:51 UTC by rvmelkonian

Closes #561.

## Changelog
• Adds a new `local_fuel_node` to the `IndexerArgs struct`.
• Updates `fuel-indexer.rs` to run the node if the flag is present.
• Brings in `fuel-core v0.17.0` to our Cargo.toml

## Testing plan 
I have done manual tests. 
•When `cargo run --bin fuel-indexer` is ran, the indexer starts, with no local fuel node.
•When `cargo run --bin fuel-indexer -- --local-fuel-node` is ran, the indexer starts and the local fuel node with default settings starts up. 
I didn't write any unit-tests or integration tests here as it didn't seem necessary, but happy to if that's preferred.

2023-02-09 20:29 UTC, ra0x3 requested changes
@rvmelkonian 
- It works! 
- Some small feedback related to default settings and feature flagging

2023-02-09 20:32 UTC, rvmelkonian commented on packages/fuel-indexer/Cargo.toml
> +fuel-core = { version = "0.17.0" }
Yes. I was worried about increasing the size of the binary also. Good idea, let's feature flag it.

2023-02-09 20:33 UTC, deekerno commented on packages/fuel-indexer/src/bin/fuel-indexer.rs
> +        let s = FuelService::new_node(Config::local_node()).await.unwrap();
You _just_ beat me to it! I think that using port 4000 would be best as the indexer expects that by default. So you could one of two things:
- Add a function to generate a configuration struct for the local node where the only change is the port
- Take whatever port the OS hands to `fuel-core` and let the indexer service know about it

I'll let you choose what you want to do. 👌🏽

2023-02-11 18:56 UTC, rvmelkonian commented
The command to run now is `cargo run --bin fuel-indexer --features local-node` 

The `FuelService` is assigned port 4000.

Because this fuel-core is an external dependancy and not within our workspace, the compiler complained abou missing types when I used the macro `if cfg!()`, so I used the cfg attribute with a scoped block instead.

2023-02-11 19:38 UTC, deekerno commented
```
~/dev/fuel/indexer rich/561-local-node
❯ ps ax | rg fuel-indexer
95660 s004  S+     0:01.42 target/debug/fuel-indexer

~/dev/fuel/indexer rich/561-local-node
❯ lsof -ti:4000
95660
```

Works for me! I'll let Rashad have the final approval as he was the one to request changes.

2023-02-11 19:50 UTC, ra0x3 approved these changes
Nice!

2023-02-11 22:47 UTC, merged