enhancement: support panic
FuelLabs/fuel-indexer pull request #714
Opened 2023-03-27 14:39 UTC by rvmelkonian

Closes #668

2023-03-28 20:05 UTC, deekerno requested changes
Looking good! Just a few comments, but the functionality is all there. 👍🏽

2023-03-28 20:05 UTC, deekerno commented on packages/fuel-indexer-macros/src/indexer.rs
> +                                let data = bincode::serialize(&abi::Panic{ contract_id: id, reason: *reason.reason() }).expect("Bad encoding,");
See comment about using a regular number type rather than `PanicReason`.

2023-03-29 10:20 UTC, rvmelkonian commented on packages/fuel-indexer-types/src/abi.rs
> +}
yep, good idea.

2023-03-29 10:22 UTC, rvmelkonian commented on docs/src/reference-guide/indexing/receipts/panic.md
> +- The reason is type PanicReason, which is an enum of `u8` variants, you can see the reason values
Yes. Thanks you.

2023-03-29 15:58 UTC, deekerno approved these changes
:shipit:

2023-03-29 17:27 UTC, merged