enhancement: allow network config from manifest
FuelLabs/fuel-indexer pull request #729
Opened 2023-04-04 16:47 UTC by ra0x3

### Description
- PR adds `fuel_node` param to indexer manifest and `--indexer-net-config` param to indexer service
- `--indexer-net-config` is set by the indexer operator, and allows indexers uploaded with a `fuel_client` manifest param, to connect to their specified Fuel client address (as opposed to the indexer node's Fuel client address)
- I added the `--indexer-net-config` flag because an indexer operator should decide whether they want to support this functionality.
  - If the indexer operator use the `--indexer-net-config` flag, then whatever is specified in the `fuel_client` param of an indexer manifest will be ignored

### Testing steps
- [ ] TBD

### Changelog 
- enhancement: allow network config from manifest

2023-04-05 18:12 UTC, rvmelkonian requested changes
This is certainly a useful flag, I can see it getting a lot of use. The test steps work and successfully connects to `beta-3`. I see this warning by the way. 
```
2023-04-05T18:07:57.057445Z  WARN fuel_indexer_lib::utils: 107: Failed to parse 'localhost:29987' as a SocketAddr due to 'invalid socket address syntax'. Retrying using ToSocketAddrs
```
Once conflicts are resolved, will approve this.

2023-04-05 18:31 UTC, rvmelkonian commented
The indexer runs and connects successfully to `beta-3.fuel.network:80`. Then if I leave the indexer running in the background (left it for about 5 minutes) I see an error 
```rust
2023-04-05T18:12:50.655199Z ERROR fuel_indexer::executor: 201: Error fetching transactions: Custom { kind: Other, error: ReqwestError(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("beta-3.fuel.network")), port: None, path: "/graphql", query: None, fragment: None }, source: hyper::Error(Io, Os { code: 60, kind: TimedOut, message: "Operation timed out" }) }) }.
```
However after this, the indexer seems to successfully reconnect again. 

Reproduce steps:

1. Git checkout `rashad/628-network-manifest-config`
2. Open the .yaml file `packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml`
3. Update the field `fuel_client` to: `beta-3.fuel.network:80` (save the file)
4. In the root of project run the command
```
cargo run --bin fuel-indexer -- run \
  --indexer-net-config \
  --manifest packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml \
  --run-migrations
  ```
  
  Full output:
  ```rust
       Running `target/debug/fuel-indexer run --indexer-net-config --manifest packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml --run-migrations`
2023-04-05T18:07:51.580883Z  INFO fuel_indexer::commands::run: 45: Configuration: IndexerConfig { verbose: false, indexer_net_config: true, fuel_node: FuelNodeConfig { host: "localhost", port: "4000" }, graphql_api: GraphQLConfig { host: "localhost", port: "29987", max_body_size: 5242880 }, database: PostgresConfig { user: "postgres", password: "XXXX", host: "localhost", port: "5432", database: "postgres", verbose: "false" }, metrics: false, stop_idle_indexers: false, run_migrations: true, authentication: AuthenticationConfig { enabled: false, strategy: None, jwt_secret: None, jwt_issuer: None, jwt_expiry: None } }
2023-04-05T18:07:51.610087Z  INFO sqlx::postgres::notice: 157: relation "_sqlx_migrations" already exists, skipping
2023-04-05T18:07:51.617527Z  INFO fuel_indexer::commands::run: 67: Using manifest file located at 'packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml'
2023-04-05T18:07:56.896092Z  INFO fuel_indexer::executor: 89: Subscribing to Fuel node at beta-3.fuel.network:80
2023-04-05T18:07:56.897042Z  INFO fuel_indexer::service: 92: Registering Asset(Schema) for Indexer(fuel_indexer_test.index1)
2023-04-05T18:07:56.933780Z  INFO fuel_indexer_postgres: 587: Registered Asset(Schema) to Indexer(fuel_indexer_test.index1).
2023-04-05T18:07:56.933883Z  INFO fuel_indexer::service: 92: Registering Asset(Manifest) for Indexer(fuel_indexer_test.index1)
2023-04-05T18:07:56.944464Z  INFO fuel_indexer_postgres: 587: Registered Asset(Manifest) to Indexer(fuel_indexer_test.index1).
2023-04-05T18:07:56.944517Z  INFO fuel_indexer::service: 92: Registering Asset(Wasm) for Indexer(fuel_indexer_test.index1)
2023-04-05T18:07:57.057168Z  INFO fuel_indexer_postgres: 587: Registered Asset(Wasm) to Indexer(fuel_indexer_test.index1).
2023-04-05T18:07:57.057264Z  INFO fuel_indexer::service: 111: Registered Indexer(fuel_indexer_test.index1)
2023-04-05T18:07:57.057445Z  WARN fuel_indexer_lib::utils: 107: Failed to parse 'localhost:29987' as a SocketAddr due to 'invalid socket address syntax'. Retrying using ToSocketAddrs.
2023-04-05T18:07:57.057987Z  INFO fuel_indexer_lib::utils: 119: Parsed SocketAddr '127.0.0.1:29987' from 'localhost:29987'
2023-04-05T18:08:09.160727Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:09.168220Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:09.177525Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:09.182758Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:09.190599Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:09.194816Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:09.202755Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:09.206702Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:09.213508Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:09.216693Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:09.223474Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:09.227325Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:16.955689Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:16.969416Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:16.989668Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:16.997155Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:17.011801Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:17.017706Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:17.029862Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:17.036261Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:17.047631Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:17.052393Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:17.060160Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:17.064075Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:17.071836Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:17.075854Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:17.089559Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:17.093501Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:24.070460Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:24.077367Z  INFO fuel_indexer::ffi: 110: fuel_indexer_test_scriptresult handling ScriptResult event.
2023-04-05T18:08:24.104596Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:24.104826Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:24.104889Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:24.104905Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:24.104919Z  INFO fuel_indexer::ffi: 110: Not subscribed to this contract. Will skip this receipt event. <('-'<)
2023-04-05T18:08:24.110691Z   [...]

2023-04-05 19:39 UTC, ra0x3 commented
@rvmelkonian Hmm after following those steps I can't seem to repro 🤔 

- What I'm _thinking_ is, maybe you have another manifest in your database? Which actually brings up a case I did not consider: the case where the service is running with the `--indexer-net-config` flag, _but_ an indexer manifest does not include the `fuel_client` param. In this case, we should just use the `FuelNodeConfig`. Good catch, I'll push up a change.

2023-04-08 16:29 UTC, rvmelkonian commented on packages/fuel-indexer/src/executor.rs
> +
👌

2023-04-08 16:30 UTC, rvmelkonian reviewed
Yep, your last commits have resolved the issue. The previous Error messages are not being thrown. Just one conflict to fix.

2023-04-10 05:22 UTC, deekerno approved these changes
I like this. 👌🏽

2023-04-10 14:14 UTC, rvmelkonian commented
Re-tested. All working well.

2023-04-10 14:26 UTC, rvmelkonian approved these changes

2023-04-10 14:26 UTC, merged