enhancement: pull remote ABI command
FuelLabs/fuel-indexer pull request #775
Opened 2023-04-19 11:36 UTC by rvmelkonian

WIP

2023-05-03 14:23 UTC, ra0x3 requested changes
@rvmelkonian Commenting on the structure of the `pull-abi` command for a bit.
- As of now, you can only download  (1) a single ABI File (which is this PR) or (2) A full contract director (with contract, ABI, manifest, etc)

- If you're downloading `#1` you'll just include your `--url` and some other option to denote that you're only wanting a single ABI file `--abi` (or whatever)
 
```bash
forc index pull-abi --url https://usercontent.github.com/raw/my_contract_abi.json --abi
```

- If you're downloading `#2` you'll include your `--url` and some other option to denote that you're only wanting to download a contract folder `--contract` (or whatever)
  - I don't think this PR should implement this (`#2`) but if you can go ahead and get this structured, and just add an `unimplemented!()` to this code path that would be super helpful.

```bash
forc index pull-abi --url https://usercontent.github.com/raw/my_contract_abi --contract
```

Also feel free to chime in here @deekerno

2023-05-03 14:23 UTC, ra0x3 commented on plugins/forc-index/src/commands/pull_abi.rs
> +    ////// URL of the ABI file
```suggestion
    /// URL of the ABI file
```

2023-05-03 14:23 UTC, ra0x3 commented on plugins/forc-index/src/commands/pull_abi.rs
> +    pub raw_url: String,
```suggestion
    pub url: String,
```

2023-05-03 14:23 UTC, ra0x3 commented on plugins/forc-index/src/commands/pull_abi.rs
> +    /// Name of contract
```suggestion
    /// Name of contract.
```

2023-05-03 14:23 UTC, ra0x3 commented on plugins/forc-index/src/ops/forc_index_pull_abi.rs
> +    let output_dir = match path {
Let's chain results where we can
```rust
   let output_dir = path.unwrap_or(std::env::current_dir().expect("Foo")); # or some such
```

2023-05-03 14:23 UTC, ra0x3 commented on plugins/forc-index/src/ops/forc_index_pull_abi.rs
> +        println!("ABI file saved to: {:?}", file_path);
```suggestion
        info!("ABI file saved to: {:?}", file_path);
```

2023-05-03 14:23 UTC, ra0x3 commented on plugins/forc-index/src/ops/forc_index_pull_abi.rs
> +    info!("✅ ABI file saved to: {:?}", file_path);
Since this is the same message as `--verbose` maybe we can shorten this?

2023-05-03 14:23 UTC, ra0x3 commented on plugins/forc-index/src/utils/defaults.rs
> +fuels = {{ version = "0.40.0", default-features = false }}
I believe this is already on master so you might want to rebase

2023-05-08 15:22 UTC, deekerno requested changes
This looks good! Just left one comment about UX.

2023-05-08 15:22 UTC, deekerno commented on plugins/forc-index/src/ops/forc_index_pull_abi.rs
> +    }
I see that `with_contract` is unimplemented; however, perhaps it's prudent to add a case in which a user passes both `with_contract` and `with_abi`. Maybe return an error saying to pick one or default to the more expansive option?

2023-05-10 18:24 UTC, deekerno approved these changes

2023-05-11 07:38 UTC, ra0x3 approved these changes

2023-05-11 07:45 UTC, merged